---
title: "Collaborative Research Proposal"
author: "Rafael Goldzweig and Rita Alvarez Martinez"
date: "28 October 2016"
bibliography: References.bib
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

I. INTRODUCTION AND RESEARCH QUESTION

The turnout rate is influenced by many factors that may be related to age, race/ethnicity, gender, socio-economic status and political/economical situation of the country. In this broad spectrum of variables that influence participation of voters in elections, this article will focus specifically on whether youth unemployment (16 to 24 years old) has an impact on turnout in the case of Spain. Youth unemployment has been a pressing issue in the country in the period of 2000-2016, when the rates were not lower than 17.5\% throughout the whole period (Source: Eurostat). In order to control for other influences related to the different profiles of the regions in the country, we will have as control variables the GDP per capita and educational levels.

This case study is interesting for the recent change in the political system of the country, that went from a party system traditionally dominated by the PP (center-right) and the PSOE (center-left) to a multy party system where the Podemos (left) and Ciudadanos (liberal/center-right) reached the national parliament with a significant vote share in the recent national elections. Our guess is that, since youth unemployment rates in Spain was significantly high in recent years as a result of the euro crisis (reaching 48.1\%  in 2015), young voters turnout or other kind of voters infleunced by their feeling of responsability towards young people were among the reasons to explain why the party system changed so drastically in recent years.  

II. LITERATURE REVIEW

Literature on voter behavior tend to rely mainly on the incumbency-oriented hypothesis, which claims that voters tend to reward or punish government in elections according to the economic performance of the country `[@norpoth1996presidents]`. In that sense, objective or subjective economic indicators such as unemployment rates, inflation, growth and other related aspects have the potential to explain part of the variance in government support `[@lewis2000economic]`.  

Citizen dissatisfaction with economic performance substantially increases the possibility to vote against the incumbent. While some authors believe that the state of employment does not have a detectable effect upon voting behavior `[@stigler1973genera]` others have reasons to believe that unemployment rates play a role depending on the political identification of the incumbent party, with left-wing governments suffering more from hign unemployment rates than right-wing governments `[@dassonneville2013economic]`. In that view, unemployment can alter voter behavior of already mobilized voters, but not mobilize additional people that are not politically active.

While many studies focus on this incumbency oriented approach, there is surprinsingly little research investigating exactly through which channels the economic aspects influences voter participation. Contrary to the general consensus emerging from existing research, some authors show that higher levels of unemployment stimulate more people to vote `[burden2012unemployment]`. This research using the U.S. case shows that the turnout gap between the employed and unemployed shrinks as state unemployment increases, suggesting that unemployment statistics invigorates rather than suppress electoral participation.

In that sense, individuals perceive job loss as a personal problem when the unemployment rate is low and a social problem when the unemployment rate is high. Therefore, job loss can be a mobilizing experience when the unemployment rate is high. In particular, "unemployed Americans' political behavior is meaningfully influenced by unemployment context to an extent that we do not observe among gainfully employed Americans" `[@incantalupo2011effects]`. This finding is particularly interesting in the context of our research. Although our study focuses on the Spanish case, we do not expect this kind of behavior to be completely different than the U.S case and this could mean that young unemployed people, in a high unemployment context, would show higher turnout in the election day affecting the political outcome. 

Data from the Spanish Center of Sociological Research collected before the general elections in the Spring of 2011, shows that 40.6\% of the Spanish young people (15 to 29 years old) felt distrust regarding politics. It is relevant to mention that a few weeks after the general election occured in 2011, the 15-M movement started. This movement was  a "response to the inability of institutional politics to deal with the problems the country had been facing since 2009" and that speed up the appearance of new political parties into the National scene such as Podemos or Ciudadanos. 

@anduiza2014mobilization point out a very interesting fact. They compared the profile of the 15-M protesters with the participants of other four major demonstrations happening in Spain during the crisis. They found that, while the four demonstrations had participants with high levels or membership to traditional organizations (between 60% and 100%) and organizations behind the demonstrations ranging from 10 to 43 years of existence, only 13% of the M-15 demonstrators were affiliated to any type of organization. Also, the organizations participating on the M-15 movements had less than 3 years of existence. The main argument is that the M-15 movements have the potential to mobilize a different profile of participants - in many cases, people traditionally less likely to have a big political participation. 

The party that benefitted the most out of this change was "Podemos". The party was founded in March 2014 by a manifesto broadcasted by Público, an online Spanish newspaper, in the aftermath of the 15-M Movement. With a left wing populist approach, it aimed to address the problems of inequality, unemployment and economic consequences of the European debt crisis. Soon after its creation, Podemos became the second largest political party in Spain by number of members after the People's Party (PP) and received 21% of the vote in the elections for the national parliament on December 2015, becoming the third largest party in the parliament in less than two years of existence. 

In this context, @jover2014political argues that the previous distrust feeling would make young Spanish voters to not to participate in the general elections of 2011. Hence, after the 15-M and with the appearance of new political options, the youth would mobilize and vote more in subsequent elections. In fact, 41.8\% of the young people answered in a survey that the 15-M movement had influenced them a lot to cast their vote in the regional elections in the Fall of 2011, months after the General Elections. It is important to mention that @jover2014political shows data from self-reported surveys and does not prove causality between youth unemployment and turnout or between the appearance of new political parties and turnout. 

In this framework, our study aims to build upon the research of economic variables affecting turnout, especially through the channel of unemployment. Without focusing directly on the change of preferences that traditionally is taken into account to analyze voter behavior, we want to see if socio-economic reasons have the potential to affect general turnout rates through the mobilization of groups traditionally not very politically active. 

III. DATA 

Our model will be tested using data from the Spanish Statistic Office (INE), the Electoral Results from the Spanish Ministry of Interior Affairs (MI), Eurostat and Expansión in the different regions of the country.

The electoral data results from 2008 and 2011 came from the same source (Spain Public Administration), while the 2015 and 2004 (media) from one source each. All of them report the results from the elections according to the Spanish Ministry of Interior Affairs. We made use of a web-scrappable interface from the websites of our sources to import the results to build our dataset. For each of the 19 regions of Spain, we used a differet URL source to grab the data available online. This process was done simmilarly with the data from 2008, 2011 and 2015. We could not find any source online that provided a web scraping friendly version from the data of 2004, and we decided to create an excel file with it. 

The unemployment rates by age data comes from the Spanish National Statistics Institute (INE). The data is available by trimester for every year and every region. We imported the data directly from the website and transformed the database to fit the ones containing the electoral results. 

Both datasets were done through web scraping and cleaned/merged using Region and Year as our common variables to form the final dataset "Spain_data".

IV. STATISTICAL MODEL AND HYPOTHESIS

Our theory is that turnout is positively impacted by higher youth unemployment rates. In that sense, we aim to reject the following hypotheses:

H0 = there is no relation between youth unemployment and turnout.

In order to analyze this relation statistically and control for differences from the distinct regions in Spain, we propose the following model:

$Turnout_{i,t}=\beta_0+\beta_1 Youth\ Unemployment_{i,t}+\beta_2 \% Young\ People + \beta_3 Youth\ Unemployment*\% Young\ People + \beta_4 \% GDP\ per \ capita + \beta_4 \% Tertiary\ Education + \delta_i + u_{i,t}$

where $i$ represents each of the 19 regions (Autonomus Communities) of Spain, $t$ represent the most recent years where general elections where held: 2004, 2008, 2011 and 2015 and $\delta_i$ represents regional fixed effects. 




##Bibliography